### ISSUE TITLE
Problems pulling images from the API

### ISSUE THREAD

**Issue by benlk** [npr/nprapi-wordpress#59]
> 2018/09/26 15:55:31 [error] 338#0: *32144 FastCGI sent in stderr: "PHP message: Cron 0 querying NPR API for https://api-s1.npr.org/query?id=1070&amp;title=title
> PHP message: Got image from: https://media-s1.npr.org/assets/img/2018/09/18/gettyimages-479699945-7e1e632c99b4301a982633ba88845cae034f1a96.jpg
> PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wp_read_image_metadata() in /Users/blk/sites/nprapi/wp-admin/includes/media.php:422
> Stack trace:
> #0 /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/classes/NPRAPIWordpress.php(337): media_handle_sideload(Array, 222, 'People work at ...')
> #1 /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/get_stories.php(68): NPRAPIWordpress->update_posts_from_stories(true, 0)
> #2 /Users/blk/sites/nprapi/wp-includes/class-wp-hook.php(286): DS_NPR_API::nprstory_cron_pull()
> #3 /Users/blk/sites/nprapi/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
> #4 /Users/blk/sites/nprapi/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
> #5 /Users/blk/sites/nprapi/wp-cron.php(126): do_action_ref_array('npr_ds_hourly_c...', Array)
> #6 /Users/blk/.composer/vendor/laravel/valet/server.php(147): require('/Users/blk/site...')
> #7 {main}
>   thrown in /Users/blk/sites/nprapi/wp-admin/includes/media.php on line 422" while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /wp-cron.php?doing_wp_cron=1537991731.0289139747619628906250 HTTP/1.1", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "nprapi.test", referrer: "http://nprapi.test/wp-cron.php?doing_wp_cron=1537991731.0289139747619628906250"

here's the key bit:

> Uncaught Error: Call to undefined function wp_read_image_metadata() in /Users/blk/sites/nprapi/wp-admin/includes/media.php:422

**Comment by benlk** [comment]
This was a one-line fix; I'll include it in work on #57 .

**Comment by benlk** [comment]
#60 has merged, so moving this to the "Done" category.
